Exercise layout by raul valencia
DkSanjed/css-tutorial pull request #10
Opened 2020-05-27 01:37 UTC by DkSanjed

New exercise

2020-05-29 18:33 UTC, juancho11gm commented on 7-layouts/style.css
> +        width: 96%;
```suggestion
        width: 100%;
```

2020-05-29 18:35 UTC, juancho11gm requested changes
Very nice Raúl!. Please see the comments and sort the rules (A-z).
![image](https://user-images.githubusercontent.com/36536646/83293366-4d83fb80-a1b1-11ea-9566-41a93652116b.png)

2020-05-31 19:06 UTC, pushdev-code requested changes

2020-05-31 19:06 UTC, pushdev-code commented on 7-layouts/style.css
> +footer {
always prefer classnames over tag names so you avoid side effects and forcing your markup to match your styles.

2020-05-31 19:06 UTC, pushdev-code commented on 7-layouts/style.css
> +    background-color: rgb(39, 39, 39);
```suggestion
    background-color: #272727;
```
If you don't use rgba + the opacity value, use hexadecimal for colors.

2020-05-31 19:06 UTC, pushdev-code commented on 7-layouts/style.css
> +    background-color: rgb(255, 255, 255, 0.25);
```suggestion
    background-color: rgb(255, 255, 255, .25);
```
0 is always nothing, so you save 1 character by doing `.25`

2020-06-02 15:54 UTC, merged