Exercise media queries by raul valencia
DkSanjed/css-tutorial pull request #9
Opened 2020-05-20 05:17 UTC by DkSanjed

Exercise media queries

2020-05-20 16:48 UTC, juancho11gm commented on 6-media-queries/style.css
> +
```suggestion
```

2020-05-20 16:49 UTC, juancho11gm requested changes
Almost perfect, you can commit it directly and it would be merged.

2020-05-24 17:30 UTC, pushdev-code requested changes
suggestion so it's mobile first and you reuse properties applied on the previous breakpoint.

2020-05-24 17:30 UTC, pushdev-code commented on 6-media-queries/style.css
> +}
```suggestion
    body {
        background-color: blue;
        color: white;
    }
    
@media screen and (min-width: 601px) and (max-width: 1023px) {
    body {
        background-color:green;
        color: black;
    }
}
@media screen and (min-width: 1024px) {
    body {
        background-color:white;
    }
}
```

2020-05-27 04:09 UTC, merged